#!/usr/bin/env python3
"""Generate every derived theme file from theme/palette.json.

Runs automatically as a pre-render step (see _quarto.yml), so the generated
files can never drift from the palette. None of them are edited by hand.

Outputs:
    theme/tokens.css          CSS custom properties for both modes
    theme/tokens.js           the palette as a browser global
    theme/_scripts.html       tokens.js + plotly-theme-sync.js, inlined
    theme/_tokens-light.scss  Bootstrap variables, light
    theme/_tokens-dark.scss   Bootstrap variables, dark

With light and dark themes configured, Quarto puts a quarto-light or
quarto-dark class on <body> — the CSS is generated against those scopes.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PALETTE = ROOT / "theme" / "palette.json"
OUT_CSS = ROOT / "theme" / "tokens.css"
OUT_JS = ROOT / "theme" / "tokens.js"
OUT_HTML = ROOT / "theme" / "_scripts.html"
SYNC_JS = ROOT / "theme" / "plotly-theme-sync.js"


def emit_vars(p: dict, mode: str) -> list[str]:
    """Build the CSS custom property list for one mode."""
    lines: list[str] = []

    # Categorical slots, numbered from 1 to match how they are described.
    for i, hex_ in enumerate(p["series"][mode], start=1):
        lines.append(f"  --viz-series-{i}: {hex_};")

    # Causal roles layered on top of the slots.
    for role, spec in p["semantic"].items():
        lines.append(f"  --viz-{role}: {p['series'][mode][spec['slot']]};")

    # Reference lines (simulation ground truth, zero).
    for name, hex_ in p["reference"][mode].items():
        lines.append(f"  --viz-ref-{name}: {hex_};")

    # Chart chrome and ink.
    for name, hex_ in p["chrome"][mode].items():
        lines.append(f"  --viz-{name}: {hex_};")

    # Sequential ramp — identical in both modes; direction is a chart decision.
    for step, hex_ in p["sequential"]["steps"].items():
        lines.append(f"  --viz-seq-{step}: {hex_};")

    # Diverging ramp.
    for pole in ("negative", "midpoint", "positive"):
        lines.append(f"  --viz-div-{pole}: {p['diverging'][pole][mode]};")

    # Status colors are fixed and never themed.
    for name, hex_ in p["status"].items():
        if not name.startswith("_"):
            lines.append(f"  --viz-status-{name}: {hex_};")

    return lines


def write_css(p: dict) -> None:
    out = [
        "/* GENERATED by scripts/build_tokens.py from theme/palette.json.",
        "   Do not edit — changes are overwritten on the next render.",
        "   Change colors in theme/palette.json. */",
        "",
        ":root,",
        "body.quarto-light {",
        *emit_vars(p, "light"),
        f"  --viz-font-sans: {p['typography']['sans']};",
        f"  --viz-font-mono: {p['typography']['mono']};",
        "}",
        "",
        "body.quarto-dark {",
        *emit_vars(p, "dark"),
        "}",
        "",
    ]
    OUT_CSS.write_text("\n".join(out), encoding="utf-8")
    n = sum(1 for line in out if line.startswith("  --"))
    print(f"build_tokens: {OUT_CSS.relative_to(ROOT)} — {n} variables")


def write_js(p: dict) -> None:
    """Emit the palette for the browser.

    Needed in two places: plotly-theme-sync.js recolors baked charts on a
    theme toggle, and OJS explorables (T3) draw from the same colors as the
    build-time charts (T1).
    """
    clean = {k: v for k, v in p.items() if not k.startswith("_")}
    for section in clean.values():
        if isinstance(section, dict):
            for key in [k for k in section if k.startswith("_")]:
                del section[key]

    # light -> dark lookup used to recolor traces, shapes and annotations on
    # the fly. Chrome is included because reference lines and labels are drawn
    # in chrome ink, and those colors are baked into the figure at build time.
    swap = dict(zip(p["series"]["light"], p["series"]["dark"]))
    swap.update(zip(p["reference"]["light"].values(), p["reference"]["dark"].values()))
    swap.update(
        (light_hex, p["chrome"]["dark"][name])
        for name, light_hex in p["chrome"]["light"].items()
        if light_hex.startswith("#") and light_hex != p["chrome"]["dark"][name]
    )
    clean["swapLightToDark"] = swap
    clean["swapDarkToLight"] = {v: k for k, v in swap.items()}

    OUT_JS.write_text(
        "// GENERATED by scripts/build_tokens.py from theme/palette.json. Do not edit.\n"
        "window.PLAYBOOK_PALETTE = "
        + json.dumps(clean, ensure_ascii=False, indent=2)
        + ";\n",
        encoding="utf-8",
    )
    print(f"build_tokens: {OUT_JS.relative_to(ROOT)} — {len(swap)} swap pairs")


def write_inline_bundle() -> None:
    """Inline both scripts into a single include.

    They cannot be referenced as files: GitHub project pages are served from a
    subpath, so an absolute /theme/... breaks, and a relative path breaks from
    inside notes/.
    """
    OUT_HTML.write_text(
        "<!-- GENERATED by scripts/build_tokens.py. Do not edit. -->\n"
        "<script>\n"
        + OUT_JS.read_text(encoding="utf-8")
        + "</script>\n<script>\n"
        + SYNC_JS.read_text(encoding="utf-8")
        + "</script>\n",
        encoding="utf-8",
    )
    print(f"build_tokens: {OUT_HTML.relative_to(ROOT)} — inline bundle written")


def write_scss(p: dict) -> None:
    """Emit Bootstrap variables.

    These compile at build time and cannot read var(--viz-*), so generating
    them is the only way to keep site chrome from drifting away from the
    chart colors.
    """
    for mode in ("light", "dark"):
        ch = p["chrome"][mode]
        scss = [
            f"// GENERATED by scripts/build_tokens.py from theme/palette.json ({mode}).",
            f"// Do not edit. Non-color rules live in theme/{mode}.scss.",
            "",
            "/*-- scss:defaults --*/",
            f"$font-family-sans-serif: {p['typography']['sans']} !default;",
            f"$font-family-monospace: {p['typography']['mono']} !default;",
            f"$body-bg: {ch['page']} !default;",
            f"$body-color: {ch['ink']} !default;",
            f"$link-color: {p['series'][mode][0]} !default;",
            f"$border-color: {ch['grid']} !default;",
            f"$code-color: {p['series'][mode][1]} !default;",
            f"$table-border-color: {ch['grid']} !default;",
            f"$card-bg: {ch['surface']} !default;",
            f"$navbar-bg: {ch['surface']} !default;",
            f"$navbar-fg: {ch['ink-2']} !default;",
            f"$sidebar-bg: {ch['page']} !default;",
            f"$sidebar-fg: {ch['ink-2']} !default;",
            f"$input-bg: {ch['surface']} !default;",
            "",
        ]
        path = ROOT / "theme" / f"_tokens-{mode}.scss"
        path.write_text("\n".join(scss), encoding="utf-8")
        print(f"build_tokens: {path.relative_to(ROOT)}")


def main() -> None:
    p = json.loads(PALETTE.read_text(encoding="utf-8"))
    write_css(p)
    write_js(p)
    write_inline_bundle()
    write_scss(p)


if __name__ == "__main__":
    main()
